### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by darredo1** [wjbmattingly/bagpipes-spacy#1]
Some of the features such as EntityCluster and TokenCluster produce an error when trying to import, though others like Normalizer and QuoteDetector do work. 
![Capture](https://github.com/user-attachments/assets/cec16993-c340-4b27-b31e-d458234fa013)

**Comment by wjbmattingly** [comment]
Ah! Thanks for finding that! I'll fix it this week!

**Comment by darredo1** [comment]
Hi @wjbmattingly just checking to see if you've had a chance to look into this?

I did post my notebook that I am using for entity clustering with a rule-based approach and you can see its unwieldy and isn't going to scale well...
https://github.com/darredo1/jfkentityruler/blob/main/pyTMCTs_Master.ipynb 

Much appreciated!

**Comment by wjbmattingly** [comment]
Thanks so much for reminding me! I just fixed it! You can now do it like this:

```python
import spacy

nlp = spacy.load("en_core_web_lg")
nlp.add_pipe("sentence_cluster", config={"threshold": 0.8})
nlp.add_pipe("token_cluster", config={"threshold": 0.4})
nlp.add_pipe("entity_cluster", config={"threshold": 0.3})
nlp.add_pipe("keyword_extractor", last=True, config={"top_n": 10, "min_ngram": 1, "max_ngram": 3, "strict": True, "top_n_sent": 3})

text = "Microsoft is a company. Twitter is another company. Tiger Woods is an athlete. Michael Jordan is an athlete."
text = text.replace("MIcrosoft", "Microsoft")
doc = nlp(text)

print(doc._.ent_cluster)
print(doc._.sent_cluster)
print(doc._.token_cluster)
# print("Top Document Keywords:", doc._.keywords)
# for sent in doc.sents:
#     print(f"Sentence: {sent.text}")
#     print("Top Sentence Keywords:", sent._.sent_keywords)
```
